twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        'src/WineBundle/Resources/views': 'WineBundle'
        'src/MovieBundle/Resources/views': 'MovieBundle'

when@test:
    twig:
        strict_variables: true
