version: '3.8'

services:
  web:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
    working_dir: /var/www/html
    container_name: manageLeisure
    ports:
      - "80:80"
      - "443:443"
    networks:
      manageLeisure:
    depends_on:
      - database
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: manageLeisureElasticsearch
    environment:
      - node.name=manageLeisure-elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      manageLeisure:
  database:
    image: mysql:8.0
    container_name: manageLeisureDb
    env_file: .env.local
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      manageLeisure:

volumes:
  esdata:
    driver: local
  mysqldata:
    driver: local

networks:
  manageLeisure:
    ipam:
      driver: default
