version: '3.8'

services:
  web:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
    working_dir: /var/www/html
    container_name: manageLeisure
    ports:
      - "80:80"
      - "443:443"
    networks:
      manageLeisure:
    depends_on:
      - database
  database:
    image: mysql:8.0
    container_name: manageLeisureDb
    env_file: .env.local
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      manageLeisure:

volumes:
  mysqldata:
    driver: local

networks:
  manageLeisure:
    ipam:
      driver: default
