version: '3.8'

services:
  web:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
      args:
        PHP_VERSION: "8.1"
        APP_ENV: prod
    working_dir: /var/www/html
    container_name: myLife
    ports:
      - "80:80"
    networks:
      myLife:
    depends_on:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - PHP_XDEBUG_ENABLED=1
      - PHP_INI_XDEBUG__CLIENT_PORT=9003
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - PHP_IDE_CONFIG=serverName=myLife
  database:
    image: mysql:8.0
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${DB_PORT}:${DB_PORT}
    container_name: myLifeDb
    env_file: .env.local
    volumes:
      - mysqldata:/var/lib/mysql
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS ${DB_DATABASE}; CREATE DATABASE IF NOT EXISTS ${TEST_DATABASE};' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    networks:
      myLife:

volumes:
  mysqldata:
    driver: local

networks:
  myLife:
    ipam:
      driver: default
