services:
  web:
    build:
      args:
        APP_ENV: prod
    volumes:
      - ./public/.well-known/acme-challenge:/var/www/html/public/.well-known/acme-challenge
    restart: always
    networks:
      manageLeisure:
        ipv4_address: 172.35.0.6
  database:
    restart: always
    ports:
      - 127.0.0.1:${DB_PORT}:${DB_PORT}
    networks:
      manageLeisure:
        ipv4_address: 172.35.0.10

networks:
  manageLeisure:
    ipam:
      driver: default
      config:
        - subnet: 172.35.0.0/24
