services:
  web:
    build:
      args:
        APP_ENV: staging
    volumes:
      - ./public/.well-known/acme-challenge:/var/www/html/public/.well-known/acme-challenge
    restart: always
  database:
    restart: always
