services:
  web:
    volumes:
      - ./public/.well-known/acme-challenge:/var/www/html/public/.well-known/acme-challenge
      - ./public/img/wine/labels:/var/www/html/public/img/wine/labels
    restart: always
    networks:
      manageLeisure:
        ipv4_address: 172.20.0.6
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: 0.5

  database:
    restart: always
    ports:
      - 127.0.0.1:${DB_PORT}:${DB_PORT}
    networks:
      manageLeisure:
        ipv4_address: 172.20.0.7
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 0.3

networks:
  manageLeisure:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
