version: '3.8'

services:
  web:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
      args:
        PHP_VERSION: "8.1"
    working_dir: /var/www/html
    container_name: manageLeisure
    ports:
      - "80:80"
    networks:
      manageLeisure:
    depends_on:
      - database
  database:
    image: mysql:8.0
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${DB_PORT}:${DB_PORT}
    container_name: manageLeisureDb
    env_file: .env.local
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      manageLeisure:

volumes:
  mysqldata:
    driver: local

networks:
  manageLeisure:
    ipam:
      driver: default
