services:
  web:
    volumes:
      - uploads:/var/www/html/uploads
      - ./public/.well-known/acme-challenge:/var/www/html/public/.well-known/acme-challenge
    restart: always
    networks:
      manageLeisure:
        ipv4_address: 172.20.0.6
  database:
    restart: always
    ports:
      - 127.0.0.1:${DB_PORT}:${DB_PORT}
    networks:
      manageLeisure:
        ipv4_address: 172.20.0.7

volumes:
  uploads:
    driver: local

networks:
  manageLeisure:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
