services:
  web:
    volumes:
      - ./public/.well-known/acme-challenge:/var/www/html/public/.well-known/acme-challenge
    restart: always
  database:
    restart: always
    ports:
      - 127.0.0.1:${DB_PORT}:${DB_PORT}
