wine_bundle:
    resource: '@WineBundle/Resources/config/routing.yaml'

kernel:
    resource: ../src/Kernel.php
    type: annotation

not_found:
    path: /{req}
    defaults: { _controller: 'App\Controller\HomepageController::notFound' }
    requirements:
        req: ".*"
