admin_bundle:
    resource: '@AdminBundle/Resources/config/routing.yaml'

movie_bundle:
    resource: '@MovieBundle/Resources/config/routing.yaml'

wine_bundle:
    resource: '@WineBundle/Resources/config/routing.yaml'

kernel:
    resource: ../src/Kernel.php
    type: annotation

uploads:
    path: /uploads/{req}
    defaults: { _controller: 'App\Controller\UploadsController::uploads' }
    requirements:
        req: ".*"

page:
    path: /{req}
    defaults: { _controller: 'App\Controller\PageController::catchAll' }
    requirements:
        req: ".*"
