wine_bundle:
    resource: '@WineBundle/Resources/config/routing.yaml'

movie_bundle:
    resource: '@MovieBundle/Resources/config/routing.yaml'

kernel:
    resource: ../src/Kernel.php
    type: annotation

uploads:
    path: /uploads/{req}
    defaults: { _controller: 'App\Controller\HomepageController::uploads' }
    requirements:
        req: ".*"

not_found:
    path: /{req}
    defaults: { _controller: 'App\Controller\HomepageController::catchAll' }
    requirements:
        req: ".*"
